services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rails
      POSTGRES_DB: job_search
    ports:
      - "5434:5432"

  web: &application
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://rails:password@db:5432/job_search
      BUNDLE_PATH: /usr/local/bundle
      GEM_HOME: /usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  runner:
    # docker-compose run --rm runner 
    <<: *application
    profiles: ["runner"]
    command: /bin/bash --init-file .init-runner
    ports:
      - '3002:3002'

volumes:
  postgres_data:
  bundle_cache: